export const SHOP_SID = 'SHOP_SID'
export const SHOP_INFO = 'SHOP_INFO'
export const SHOP_SIGN_INFO = 'SHOP_SIGN_INFO'
export const UPDATE_SHOP_INFO = 'UPDATE_SHOP_INFO'
export const SHOP_DELIVERS = 'SHOP_DELIVERS'